version: 2.1
jobs:
  build-one:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'           
  build-two:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The Second Step
          command: |
            echo 'This is the delivery pipeline'
workflows:
  version: 2
  build-one_build-two:
    jobs:
      - build-one
      - build-two
